//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamworkTF.Sharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamworkTF.Sharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teamwork.tf/api/v1/{0}{1}key={2}.
        /// </summary>
        internal static string API_LINK {
            get {
                return ResourceManager.GetString("API_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gamemap-creator/steamid/{0}.
        /// </summary>
        internal static string CREATORS_MAP {
            get {
                return ResourceManager.GetString("CREATORS_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube-creator/steamid/{0}.
        /// </summary>
        internal static string CREATORS_YOUTUBE {
            get {
                return ResourceManager.GetString("CREATORS_YOUTUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server address you have provided is invalid. Please provide a valid address like: 193.221.192.28.
        /// </summary>
        internal static string ERROR_INVALID_IP {
            get {
                return ResourceManager.GetString("ERROR_INVALID_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API key must be provided. Go to: https://teamwork.tf/settings and look for your API key under &apos;Show optional settings&apos;..
        /// </summary>
        internal static string ERROR_INVALID_KEY {
            get {
                return ResourceManager.GetString("ERROR_INVALID_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map-stats/mapimages/{0}.
        /// </summary>
        internal static string MAP_IMAGES {
            get {
                return ResourceManager.GetString("MAP_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map-stats/search?search_term={0}.
        /// </summary>
        internal static string MAP_SEARCH {
            get {
                return ResourceManager.GetString("MAP_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map-stats/map/{0}.
        /// </summary>
        internal static string MAP_STATS {
            get {
                return ResourceManager.GetString("MAP_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map-stats/mapthumbnail/{0}.
        /// </summary>
        internal static string MAP_THUMBNAIL {
            get {
                return ResourceManager.GetString("MAP_THUMBNAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        internal static string NEWS {
            get {
                return ResourceManager.GetString("NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news/hash/{0}.
        /// </summary>
        internal static string NEWS_HASH {
            get {
                return ResourceManager.GetString("NEWS_HASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news?page={0}.
        /// </summary>
        internal static string NEWS_PAGE {
            get {
                return ResourceManager.GetString("NEWS_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news?provider={0}.
        /// </summary>
        internal static string NEWS_PROVIDER {
            get {
                return ResourceManager.GetString("NEWS_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teamwork.tf/community/quickplay/{0}:27015/550x125.png.
        /// </summary>
        internal static string SERVER_BANNER {
            get {
                return ResourceManager.GetString("SERVER_BANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to community/provider/{0}.
        /// </summary>
        internal static string SERVER_COMM_SEARCH {
            get {
                return ResourceManager.GetString("SERVER_COMM_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to community/provider/{0}/servers.
        /// </summary>
        internal static string SERVER_COMM_SERVERS {
            get {
                return ResourceManager.GetString("SERVER_COMM_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to community/provider/{0}/stats.
        /// </summary>
        internal static string SERVER_COMM_STATS {
            get {
                return ResourceManager.GetString("SERVER_COMM_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to competitive/provider/{0}.
        /// </summary>
        internal static string SERVER_COMP_SEARCH {
            get {
                return ResourceManager.GetString("SERVER_COMP_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to competitive/provider/{0}/stats.
        /// </summary>
        internal static string SERVER_COMP_STATS {
            get {
                return ResourceManager.GetString("SERVER_COMP_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customserverlist.
        /// </summary>
        internal static string SERVER_CUSTOM_LIST {
            get {
                return ResourceManager.GetString("SERVER_CUSTOM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customserverlist/{0}.
        /// </summary>
        internal static string SERVER_CUSTOM_SEARCH {
            get {
                return ResourceManager.GetString("SERVER_CUSTOM_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customserverlist/{0}/servers.
        /// </summary>
        internal static string SERVER_CUSTOM_SERVERS {
            get {
                return ResourceManager.GetString("SERVER_CUSTOM_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay/server?ip={0}&amp;port={1}.
        /// </summary>
        internal static string SERVER_IP_FULL {
            get {
                return ResourceManager.GetString("SERVER_IP_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay/server?ip={0}.
        /// </summary>
        internal static string SERVER_IP_NOPORT {
            get {
                return ResourceManager.GetString("SERVER_IP_NOPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay.
        /// </summary>
        internal static string SERVER_MODES {
            get {
                return ResourceManager.GetString("SERVER_MODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay/{0}/servers.
        /// </summary>
        internal static string SERVER_MODES_LIST {
            get {
                return ResourceManager.GetString("SERVER_MODES_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quickplay/{0}.
        /// </summary>
        internal static string SERVER_MODES_SEARCH {
            get {
                return ResourceManager.GetString("SERVER_MODES_SEARCH", resourceCulture);
            }
        }
    }
}
